# Use an official Python runtime as a parent image
FROM python


# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .



RUN python -m pip install --no-cache-dir --upgrade -r /app/requirements.txt

RUN python -m pip install --break-system-packages git+https://github.com/dpkp/kafka-python.git

CMD ["python", "post_data_to_postgres_and_kafka.py"]

