version: 2

sources:
  
  - name: src_oltp
    database: postgres #cross-database references are not implemented . Ensure database name matches the one in profile.yml 
    schema: schema_datawarehouse_landingzone
    freshness:
      warn_after:
        count: 1
        period: minute 
      error_after:
        count: 5
        period: hour
    loaded_at_field: timestamp

    tables:
      - name: raw_trips
        identifier: raw_trips
        columns:
          - name: id
            tests:
              - not_null
          - name: measurement_time
            tests:
              - not_null
        freshness:
          warn_after:
            count: 5
            period: hour
          error_after:
            count: 2
            period: day
        loaded_at_field: loaded_at