
# Use an official  image as a parent image
FROM python

# Update package lists, install necessary packages, and clean up in one RUN to reduce image size
RUN apt-get update && apt-get install -y \
    # build-essential \
    # wget \
    curl \
    # telnet \
    cron \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .


# Ensure entrypoint.sh is executable
# COPY config_debezium_postgres_connector.sh /usr/local/bin/
RUN chmod +x config_debezium_postgres_connector.sh



