{% macro us_state_abbreviation(column_name) %}
    CASE 
    WHEN UPPER({{ column_name }}) = 'ALABAMA' THEN 'AL'
    WHEN UPPER({{ column_name }}) = 'ALASKA' THEN 'AK'
    WHEN UPPER({{ column_name }}) = 'ARIZONA' THEN 'AZ'
    WHEN UPPER({{ column_name }}) = 'ARKANSAS' THEN 'AR'
    WHEN UPPER({{ column_name }}) = 'CALIFORNIA' THEN 'CA'
    WHEN UPPER({{ column_name }}) = 'COLORADO' THEN 'CO'
    WHEN UPPER({{ column_name }}) = 'CONNECTICUT' THEN 'CT'
    WHEN UPPER({{ column_name }}) = 'DELAWARE' THEN 'DE'
    WHEN UPPER({{ column_name }}) = 'DISTRICT OF COLUMBIA' THEN 'DC'
    WHEN UPPER({{ column_name }}) = 'FLORIDA' THEN 'FL'
    WHEN UPPER({{ column_name }}) = 'GEORGIA' THEN 'GA'
    WHEN UPPER({{ column_name }}) = 'HAWAII' THEN 'HI'
    WHEN UPPER({{ column_name }}) = 'IDAHO' THEN 'ID' 
    WHEN UPPER({{ column_name }}) = 'ILLINOIS' THEN 'IL'
    WHEN UPPER({{ column_name }}) = 'INDIANA' THEN 'IN'
    WHEN UPPER({{ column_name }}) = 'IOWA' THEN 'IA'
    WHEN UPPER({{ column_name }}) = 'KANSAS' THEN 'KA'
    WHEN UPPER({{ column_name }}) = 'KENTUCKY' THEN 'KY'
    WHEN UPPER({{ column_name }}) = 'LOUISIANA' THEN 'LA'
    WHEN UPPER({{ column_name }}) = 'MAINE' THEN 'ME'
    WHEN UPPER({{ column_name }}) = 'MARYLAND' THEN 'MD'
    WHEN UPPER({{ column_name }}) = 'MASSACHUSETTS' THEN 'MA'
    WHEN UPPER({{ column_name }}) = 'MICHIGAN' THEN 'MI'
    WHEN UPPER({{ column_name }}) = 'MINNESOTA' THEN 'MN'
    WHEN UPPER({{ column_name }}) = 'MISSISSIPPI' THEN 'MS' 
    WHEN UPPER({{ column_name }}) = 'MISSOURI' THEN 'MO'
    WHEN UPPER({{ column_name }}) = 'MONTANA' THEN 'MT'
    WHEN UPPER({{ column_name }}) = 'NEBRASKA' THEN 'NE'
    WHEN UPPER({{ column_name }}) = 'NEVADA' THEN 'NV'
    WHEN UPPER({{ column_name }}) = 'NEW HAMPSHIRE' THEN 'NH'
    WHEN UPPER({{ column_name }}) = 'NEW JERSEY' THEN 'NJ'
    WHEN UPPER({{ column_name }}) = 'NEW MEXICO' THEN 'NM'
    WHEN UPPER({{ column_name }}) = 'NEW YORK' THEN 'NY'
    WHEN UPPER({{ column_name }}) = 'NORTH CAROLINA' THEN 'NC'
    WHEN UPPER({{ column_name }}) = 'NORTH DAKOTA' THEN 'ND'
    WHEN UPPER({{ column_name }}) = 'OHIO' THEN 'OH'
    WHEN UPPER({{ column_name }}) = 'OKLAHOMA' THEN 'OK' 
    WHEN UPPER({{ column_name }}) = 'OREGON' THEN 'OR'
    WHEN UPPER({{ column_name }}) = 'PENNSYLVANIA' THEN 'PA'
    WHEN UPPER({{ column_name }}) = 'RHODE ISLAND' THEN 'RI'
    WHEN UPPER({{ column_name }}) = 'SOUTH CAROLINA' THEN 'SC'
    WHEN UPPER({{ column_name }}) = 'SOUTH DAKOTA' THEN 'SD'
    WHEN UPPER({{ column_name }}) = 'TENNESSEE' THEN 'TN'
    WHEN UPPER({{ column_name }}) = 'TEXAS' THEN 'TX'
    WHEN UPPER({{ column_name }}) = 'UTAH' THEN 'UT'
    WHEN UPPER({{ column_name }}) = 'VERMONT' THEN 'VT'
    WHEN UPPER({{ column_name }}) = 'VIRGINIA' THEN 'VA'
    WHEN UPPER({{ column_name }}) = 'WASHINGTON' THEN 'WA'
    WHEN UPPER({{ column_name }}) = 'WEST VIRGINIA' THEN 'WV'
    WHEN UPPER({{ column_name }}) = 'WISCONSIN' THEN 'WI'
    WHEN UPPER({{ column_name }}) = 'WYOMING' THEN 'WY'
    ELSE UPPER({{ column_name }})
    END
{% endmacro %}