datawarehouse:
  outputs:
    local:
      type: postgres
      host: localhost #postgres_for_datawarehouse
      user: admin
      password: password
      port: 5434 #5432
      dbname: postgres # or database instead of dbname
      schema: caleb_dev
      threads: 8
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      # search_path: [optional, override the default postgres search_path]
      # role: [optional, set the role dbt assumes when executing queries]
      # sslmode: [optional, set the sslmode used to connect to the database]
      # sslcert: [optional, set the sslcert to control the certifcate file location]
      # sslkey: [optional, set the sslkey to control the location of the private key]
      # sslrootcert: [optional, set the sslrootcert config value to a new file path in order to customize the file location that contain root certificates]
  

    docker:
      type: postgres
      host: 172.20.0.7
      user: admin
      password: password
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: caleb_dev
      threads: 8
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      # search_path: [optional, override the default postgres search_path]
      # role: [optional, set the role dbt assumes when executing queries]
      # sslmode: [optional, set the sslmode used to connect to the database]
      # sslcert: [optional, set the sslcert to control the certifcate file location]
      # sslkey: [optional, set the sslkey to control the location of the private key]
      # sslrootcert: [optional, set the sslrootcert config value to a new file path in order to customize the file location that contain root certificates]
  
  target: docker